---
- name: Create virtual-router object
  command: >
    docker run opencontrail/config:2.20 /usr/share/contrail-utils/provision_vrouter.py
    --api_server_ip {{ opencontrail_master_host_address }}
    --host_name "{{ ansible_hostname }}{% if hostvars[inventory_hostname]['ansible_domain'] != "" %}.{{ hostvars[inventory_hostname]['ansible_domain'] }}{% endif %}"
    --host_ip "{{ opencontrail_host_address }}"
  delegate_to: "{{ groups['masters'][0] }}"
